services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop
      POSTGRES_DB: workshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshop -d workshop"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_URL: postgres://workshop:workshop@db:5432/workshop
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_PER_MINUTE: 60
      DB_POOL_MAX: 10
      WORKER_DELAY_MS: 250
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "src/worker.js"]
    environment:
      REDIS_URL: redis://redis:6379
      WORKER_DELAY_MS: 250
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  gateway:
    image: haproxy:3.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./infra/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3001:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  loadtest:
    build:
      context: .
      dockerfile: loadtest.Dockerfile
    profiles: ["loadtest"]
    depends_on:
      - gateway

volumes:
  postgres_data:
  redis_data:
  grafana_data:
